// <auto-generated />
using System;
using Facturacion.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Facturacion.Api.Migrations
{
    [DbContext(typeof(FacturacionDbContext))]
    [Migration("20260927212045_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Facturacion.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Identificacion")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoIdentificacion")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Identificacion")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Identificacion = "9999999999999",
                            Nombre = "Consumidor Final",
                            TipoIdentificacion = 3
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Direccion = "Av. Daniel León Borja y Chile, Riobamba",
                            Email = "compras@comercialriobamba.ec",
                            Identificacion = "0601234567001",
                            Nombre = "Comercial Riobamba S.A.",
                            Telefono = "032950123",
                            TipoIdentificacion = 1
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Direccion = "Calbay y Primera Constituyente, Riobamba",
                            Email = "mafe.quizhpi@mail.com",
                            Identificacion = "0603456789",
                            Nombre = "María Fernanda Quizhpi",
                            Telefono = "0987654321",
                            TipoIdentificacion = 0
                        });
                });

            modelBuilder.Entity("Facturacion.Api.Models.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FacturaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesFactura");
                });

            modelBuilder.Entity("Facturacion.Api.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIva")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Facturacion.Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Codigo = "HW-001",
                            Descripcion = "Car Culture - Japan Historics",
                            Nombre = "Hot Wheels Nissan Skyline GT-R (BNR34)",
                            PorcentajeIva = 15m,
                            Precio = 12.50m,
                            Stock = 8
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Codigo = "HW-002",
                            Descripcion = "Boulevard - STH",
                            Nombre = "Hot Wheels '70 Dodge Charger",
                            PorcentajeIva = 15m,
                            Precio = 25.00m,
                            Stock = 3
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Codigo = "HW-003",
                            Descripcion = "Premium - Euro Speed",
                            Nombre = "Hot Wheels Porsche 911 GT3 RS",
                            PorcentajeIva = 15m,
                            Precio = 9.99m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Codigo = "SV-001",
                            Nombre = "Servicio de desarrollo de software (hora)",
                            PorcentajeIva = 15m,
                            Precio = 25.00m,
                            Stock = 999
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Codigo = "LB-001",
                            Nombre = "Novela digital - Capítulos compilados",
                            PorcentajeIva = 0m,
                            Precio = 4.99m,
                            Stock = 500
                        });
                });

            modelBuilder.Entity("Facturacion.Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rol")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@facturacion.app",
                            Nombre = "Administrador Demo",
                            PasswordHash = "$2a$11$kSg0JBib7cgq.yS9QbDwf.iy5dEAA0WjyWYLjmEh.S9qm//nqIg4S",
                            Rol = 1
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "vendedor@facturacion.app",
                            Nombre = "Vendedor Demo",
                            PasswordHash = "$2a$11$qcx6yyVjcElKjcrbM/KIO.vThaVt9l.BNDTUJqDRf8DvcZRgyTj6C",
                            Rol = 0
                        });
                });

            modelBuilder.Entity("Facturacion.Api.Models.DetalleFactura", b =>
                {
                    b.HasOne("Facturacion.Api.Models.Factura", "Factura")
                        .WithMany("Detalles")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Facturacion.Api.Models.Producto", "Producto")
                        .WithMany("Detalles")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Facturacion.Api.Models.Factura", b =>
                {
                    b.HasOne("Facturacion.Api.Models.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Facturacion.Api.Models.Cliente", b =>
                {
                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Facturacion.Api.Models.Factura", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("Facturacion.Api.Models.Producto", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
